### ISSUE TITLE
Close button in Modal component is not working

### ISSUE THREAD

**Issue by andres-bedolla** [dd3tech/bui#77]
**Describe the bug**
After upgrading to v6.0.0, the close button in Modal component is not detecting any click action, and can't be closed by that way. In short, the callback function defined in the setCloseModal is not calling by clicking on the button. This behavior didn't occurred, at least in the last version that I used (v5.0.3).

**To Reproduce**
1. Create any Modal component with its required functions (active and setCloseModal) and props.
2. Open the modal.
3. Try to close the modal by clicking the close button.

**Expected behavior**
The modal should close after clicking the close button, or at least detecting any call to the callback function defined in the setCloseModal prop by clicking on it.

**Desktop (please complete the following information):**
 - OS macOS Monterey
 - Browser Chrome
 - Version 111.0.5563.146 (arm64)

**Comment by andres-bedolla** [comment]
I noticed that this only happens when the preventClose props is defined, but didn't behave like that in previous versions. I was expecting that the modal only can be close by clicking on the close button and not by clicking outside the modal or even pressing esc. 

So I don't know if this is a bug or new feature of the component, as it didn't happened before, but I was wondering if there is a workaround for achieving the behavior that I just mentioned? 

Thanks!

**Comment by tbor00** [comment]
The `preventClose` prop is used in modals to prevent accidental closure by the user. It is typically used in modals that require some confirmation before closing.

However, if you are looking for a new feature that allows the modal to remain open when the overlay is clicked, you can submit a feature request instead of reporting a bug.

The updated description of the issue could be something like:

"I am requesting a new feature for the modal component that prevents it from closing when the overlay is clicked. Currently, the preventClose prop prevents accidental closure, but I would like a new prop or functionality added to prevent the modal from closing when the overlay is clicked. This would be useful in cases where confirmation is required before closing the modal."

Thank you!
